site_name: shesha-docs
repo_url: https://github.com/boxfusion/shesha-docs
repo_name: boxfusion/shesha-docs
edit_uri: edit/main/docs/
copyright: Copyright &copy; Boxfusion
extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/
theme:
  logo: assets/logo.png
  homepage: https://shesha.io
  name: material
  palette:
    primary: deep orange
  features:
    - navigation.sections
markdown_extensions:
  - admonition
  - pymdownx.tabbed
  - pymdownx.highlight
  - pymdownx.superfences
  

